server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?userSSl=false&serverTimezone=UTC&allowpublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
mybatis:
  type-aliases-package: com.example.VMSbootdemo.bean
  mapper-locations: classpath:mapper/*mapper.xml

logging:
  level:
    com:
      exampe:
        mapper: debug